name: Publish

on:
  push:
    tags:
      - v*
jobs:
  publish:
    name: Publish (${{ matrix.os }} - ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: x64

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Generate Windows code signing certificate 
        if: matrix.os == 'windows-latest'
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'windows-certificate.pfx'
          encodedString: ${{ secrets.WINDOWS_CODESIGN_CERTIFICATE }}
      - name: Generate MacOS code signing certificate
        if: matrix.os == 'macos-latest'
        run: ./scripts/add-macos-cert.sh
        env:
          MACOS_CERT_P12: ${{ secrets.MACOS_CERT_P12 }}
          MACOS_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
      - name: Make and Publish
        run: pnpm run publish --arch=${{ matrix.arch }}
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          WINDOWS_CERTIFICATE_FILE: ${{ steps.write_file.outputs.filePath }}
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CODESIGN_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
